
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 3;
  public static final int EQU = 6;
  public static final int EOFILE = 10;
  public static final int SEMI = 5;
  public static final int EOF = 0;
  public static final int STRING = 4;
  public static final int VAR = 2;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int SPACE = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INT",
  "STRING",
  "SEMI",
  "EQU",
  "COMMA",
  "ID",
  "SPACE",
  "EOFILE"
  };
}

