/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_program_1(char *host, int x, int y)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROGRAM, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */	

	calc_1_arg.a = x;
	calc_1_arg.b = y;

	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	else
	{
		printf("\nProgrammed by S Abhishek (AM.EN.U4CSE19147)\n");
		printf("\nThe Result of Calculation is %d.\n\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	calc_program_1 (host, atoi(argv[2]), atoi(argv[3]));
exit (0);

}
