#!/bin/bash

echo -e "\nFrom : $1    To : $2    cc : abc@domain.com" 

echo -e "\nSubject : $3"

echo -e "\n              This email is generated by my shell script."

echo -e "\nThanks and regards"

echo "S4 CSE student"

echo -e "Amritapuri\n"
