#!/bin/bash

echo -e "\n$1"

echo -e "\nFrom : $2    To : $3    cc : abc@domain.com" 

echo -e "\nSubject : $4"

echo -e "\n              This email is generated by my shell script."

echo -e "\nThanks and regards"

echo "S4 CSE student"

echo -e "Amritapuri\n"
