import java_cup.runtime.*;

scan with {: return getScanner().next_token(); :};


terminal VAR, INT, FLOAT, STRING, SEMI, EQU, ID, SPACE, NULL, EOFILE;

non terminal prog, decln, type, s, varlist;


s ::= prog {: System.out.println("Valid declaration"); :}

EOFILE{:System.exit(0);:};

prog ::= prog decln | decln;

decln ::= VAR SPACE type SPACE varlist SEMI SPACE decln | VAR SPACE type SPACE varlist SEMI;

type ::= INT | FLOAT | STRING;

varlist ::= ID SPACE EQU SPACE NULL;