
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int EQU = 6;
  public static final int EOFILE = 14;
  public static final int LCB = 11;
  public static final int SEMI = 5;
  public static final int EOF = 0;
  public static final int STRING = 4;
  public static final int RB = 10;
  public static final int RCB = 12;
  public static final int ID = 7;
  public static final int COMMA = 13;
  public static final int LB = 9;
  public static final int error = 1;
  public static final int SPACE = 8;
  public static final int FLOAT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "STRING",
  "SEMI",
  "EQU",
  "ID",
  "SPACE",
  "LB",
  "RB",
  "LCB",
  "RCB",
  "COMMA",
  "EOFILE"
  };
}

