/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
calc_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	if ( argp -> c == 1 )
	{
		printf("- Addition of %d and %d is %d.\n\n", argp->a, argp->b, ( argp->a + argp->b ) );
		result = argp->a + argp->b;
	}

	else if ( argp -> c == 2 )
	{
		printf("- Subtraction of %d and %d is %d.\n\n", argp->a, argp->b, ( argp->a - argp->b ) );
		result = argp->a - argp->b;
	}	

	else if ( argp -> c == 3 )
	{
		printf("- Multiplication of %d and %d is %d.\n\n", argp->a, argp->b, ( argp->a * argp->b ) );
		result = argp->a * argp->b;
	}

	else if ( argp -> c == 4 )
	{
		printf("- Division of %d and %d is %d.\n\n", argp->a, argp->b, ( argp->a / argp->b ) );
		result = argp->a / argp->b;
	}

	else if ( argp -> c == 5 )
	{
		printf("- Modulo of %d and %d is %d.\n\n", argp->a, argp->b, ( argp->a % argp->b ) );
		result = argp->a % argp->b;
	}

	else
	{
		result = 0;
	}

	return &result;
}
