/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calc_program_1(char *host, int x, int y, int z)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  calc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROGRAM, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */	

	calc_1_arg.a = x;
	calc_1_arg.b = y;
	calc_1_arg.c = z;

	result_1 = calc_1(&calc_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "Call failed");
	}

	else
	{
		printf("\nThe Result of Calculation is %d.\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;

	int op, a, b;

	if (argc < 2) 
	{
		printf ("usage: %s server_host\n", argv[0]);
	
		exit (1);
	}

	host = argv[1];

	while(1)
	{
	    printf("\nHey folks, You are now experimenting the Calculator programmed by S Abhishek (AM.EN.U4CSE19147)");
	
	    printf("\n\n\t\t\tAvailable OPTIONS");

	    printf("\n\n\t\tAddition - 1");

	    printf("\n\t\tSubtraction - 2");

	    printf("\n\t\tMultiplication - 3");

	    printf("\n\t\tDivision - 4");

	    printf("\n\t\tModulo - 5");

	    while(1)
	    {

		    printf("\n\nChoose your OPTION : ");
    
		    scanf("%d", &op);
	
		    if ( op == 1 )
		    {
			    printf("\nYo! You have chosen Addition :)");
			    break;
		    }

		    else if ( op == 2 )
		    {
		        printf("\nYo! You have chosen Subtraction :)");
			    break;
		    }

		    else if ( op == 3 )
		    {
			    printf("\nYo! You have chosen Multiplication :)");
			    break;
		    }

		    else if ( op == 4 )
		    {
			    printf("\nYo! You have chosen Division :)");
			    break;
		    }

		    else if ( op == 5 )
		    {
			    printf("\nYo! You have chosen Modulo :)");
			    break;
		    }

		    else
		    {
			    printf("\nYo! No such OPTION :(");
		    }	
	    }

	    printf("\n\nEnter the Number 1 : ");
    
	    scanf("%d", &a);

	    printf("Enter the Number 2 : ");
    
	    scanf("%d", &b);

	    calc_program_1 (host, a, b, op);
	    
	    printf("\nYou wanna go one more round??");
	    
	    printf("\n\n\t\tContinue - 1");

	    printf("\n\t\tExit - 2");

	    printf("\n\nChoose your OPTION : ");
    
	    scanf("%d", &op); 
	    
	    if ( op == 2 )
	    {
	        printf("\nBye!! :) :)\n\n");
	        break;
	    }
	    
	}
	
	exit (0);

}
